// react/web/src/mainAA/MainAA.tsx
import React, { Component, useEffect, useState } from 'react';
import { Card } from 'primereact/card';
import gordon from '../assets/gordonPlant.jpg'
import chris from '../assets/pexels-chris-hepworth-16047549.jpg'
import christ from '../assets/pexels-christyn-reyes-13458334.jpg'
import josh from '../assets/pexels-josh-withers-16978839.jpg'
import stjin from '../assets/pexels-stijn-dijkstra-16747506 (1).jpg'
import MyService from '../service/Service';
import './MainAA.css'

interface MainAAProps {
    size: string;
    level: string;
}

const myService = new MyService();

const MainAA: React.FC<MainAAProps> = ({ size, level }) => {
    const [currentLevel, setCurrentLevel] = useState<string>('');
    useEffect(() => {
        setCurrentLevel('AA')
    }, [])




    const headerGordon = (
        <img alt="Card" src={gordon} />
    );
    const headerChris = (
        <img alt="Card" src={chris} />
    );
    const headerChrist = (
        <img alt="Card" src={christ} />
    );
    const headerJosh = (
        <img alt="Card" src={josh} />
    );
    const headerStjin = (
        <img alt="Card" src={stjin} />
    );
    return (
        <div>
            <div className="welcome">
                <h1 tabIndex={0}>Welcome</h1>
                <h2 tabIndex={0}>Home Level AA</h2>
            </div>
            <div className='contentContainer'>
                <div className="card">
                    <Card className='card' title="Title" subTitle="Subtitle" header={headerGordon} >
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card title="Title" subTitle="Subtitle" className='card' header={headerChris} >
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card title="Title" subTitle="Subtitle" header={headerChrist} className="card">
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card title="Title" subTitle="Subtitle" header={headerJosh} className="card">
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card title="Title" subTitle="Subtitle" header={headerStjin} className="card">
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
            </div >
        </div>
    );
}

export default MainAA;

// angular/web/src/app/main-aa/main-aa.component.ts
import { Component, OnInit } from '@angular/core';
import { MenuItem } from "primeng/api";
import { DataService } from '../service/data.service';
import { Router } from '@angular/router';
import { LocationService } from '../service/location.service';

@Component({
  selector: 'app-main-aa',
  templateUrl: './main-aa.component.html',
  styleUrls: ['./main-aa.component.css']
})
export class MainAAComponent implements OnInit {
  menuItems: MenuItem[];
  menuHome: MenuItem;
  value: any;
  birthday: Date;
  size: string;

  constructor(private data: DataService, private location: LocationService, private router: Router) {
  }


  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message)
    this.location.currentLocation = 'main';
    this.menuHome = { icon: "pi pi-home" }
    this.menuItems = [
      { label: "register", url: "/register/A" },
      { label: "ReactJS" },
      { label: "HTML" },
      { label: "JavaScript" },
      { label: "PrimeNG" },
    ];
  }

  handleClick(link: string) {
    this.redirectToAnotherPage(link);
  }

  handleKeyDown(event: KeyboardEvent, link: string) {
    if (event.key === 'Enter') {
      this.redirectToAnotherPage(link);
    }
  }

  redirectToAnotherPage(link: string) {
    this.router.navigate(['/' + link]);
  }

}

<p-breadcrumb styleClass="custom-breadcrumb" class="max-w-full" [model]="menuItems"
    [home]="{ icon: ' pi pi-home' }"></p-breadcrumb>
<div class="contentContainer">
    <p-card (click)="handleClick('/register/AA')" (keydown)="handleKeyDown($event, '/register/AA')" header="Topic 1"
        tabindex="0" subheader="Very interesting" [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="Card" src="https://primefaces.org/cdn/primeng/images/usercard.png" />
        </ng-template>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
    <p-card (click)="handleClick('/register/AA')" (keydown)="handleKeyDown($event, '/register/AA')" header="Topic 2"
        subheader="must see" tabindex="0" [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="Card" src="https://primefaces.org/cdn/primeng/images/usercard.png" />
        </ng-template>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
    <p-card (click)="handleClick('/register/AA')" (keydown)="handleKeyDown($event, '/register/AA')" header="Topic 3"
        subheader="Boring" tabindex="0" [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="Card" src="https://primefaces.org/cdn/primeng/images/usercard.png" />
        </ng-template>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
    <p-card (click)="handleClick('/register/AA')" (keydown)="handleKeyDown($event, '/register/AA')" header="Topic 4"
        subheader="Good Good Good" tabindex="0" [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="Card" src="https://primefaces.org/cdn/primeng/images/usercard.png" />
        </ng-template>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
    <p-card (click)="handleClick('/register/AA')" (keydown)="handleKeyDown($event, '/register/AA')" header="Topic 5"
        subheader="Card Subheader" tabindex="0" [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="Card" src="https://primefaces.org/cdn/primeng/images/usercard.png" />
        </ng-template>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
</div>
