// angular/web/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { MenuItem } from "primeng/api";
import { DataService } from './service/data.service';
import { LocationService } from './service/location.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message)
    this.data.currentLevel.subscribe(level => this.level = level)
    this.data.currentForeground.subscribe(color => this.foreground = color);
    this.data.currenBackground.subscribe(color => this.background = color);
  }

  constructor(private data: DataService, private location: LocationService) {
    document.getElementById
  }

  title = 'Accessibility possibility of implementation';
  menuItems: MenuItem[] = this.location.breadcrumbLocation;

  isExpanded: boolean = false;
  isSize: boolean = false;
  size: string = "size1";
  foreground: string = "#000000";
  background: string = "#ffffff";
  level: string = "A";

  path: string = '';
  isRegister = this.location.isRegister;

  size1: boolean = true;
  size150: boolean = false;
  size200: boolean = false;


  items: MenuItem[] = [
    { label: 'Level A', tabindex: "0", target: "_self" },
    { label: 'Level AA', tabindex: "0", target: "_self" },
    { label: 'Level AAA', tabindex: "0", target: "_self" },
    { separator: true },
    { label: 'Font size up 50%', command: () => this.upSize(), tabindex: "0" },
    { label: 'Font size down 50%', command: () => this.downSize(), tabindex: "0" },

  ]

  getCurrentLocation(): void {
    this.items[0].url = this.location.currentLocation + '/A';
    this.items[1].url = this.location.currentLocation + '/AA';
    this.items[2].url = this.location.currentLocation + '/AAA';
  }

  changeForeground(): void {
    this.data.changeForegorund(this.foreground);
  }

  changeBackground(): void {
    this.data.changeBackgorund(this.background);
  }

  upSize() {
    if (this.size == "size1") {
      this.data.changeMessage("size15");
      return
    }
    if (this.size == "size15") {
      this.data.changeMessage("size2");
      return
    }
    if (this.size == "size2") {
      this.data.changeMessage("size2");
      return
    }
  }

  downSize() {
    if (this.size == "size1") {
      this.data.changeMessage("size1");
      return
    }
    if (this.size == "size15") {
      this.data.changeMessage("size1");
      return
    }
    if (this.size == "size2") {
      this.data.changeMessage("size15");
      return
    }
  }

  expandLinks() {
    this.isExpanded = true;
  }

  collapseLinks() {
    this.isExpanded = false;
  }

  toggleLinks() {
    this.isExpanded = !this.isExpanded;
  }

  expandSize() {
    this.isSize = true;
  }

  collapseSize() {
    this.isSize = false;
  }

  toggleSize() {
    this.isSize = !this.isSize;
  }



}

<header>
    <h2>Accessibility Test</h2>
    <nav class="navbar">
        <ul class="navLinks">
            <li><a routerLink="" tabindex="0" target="_self">Home</a></li>
            <li><a href="/register/A" tabindex="0" target="_self">About</a></li>
            <li><a href="#" tabindex="0" target="_self">Contact</a></li>
        </ul>
    </nav>
    <div class="abutton">
        <p-toast></p-toast>
        <p-menu (onShow)="getCurrentLocation()" #menu [model]="items" [popup]="true" tabindex="4"></p-menu>
        <button pButton type="button" (click)="menu.toggle($event)" icon="pi pi-bars" label="A11y Menu"></button>
        <p-colorPicker [(ngModel)]="foreground" (onChange)="changeForeground()"></p-colorPicker>
        <p-colorPicker [(ngModel)]="background" (onChange)="changeBackground()"></p-colorPicker>
    </div>
</header>
<p-breadcrumb styleClass="custom-breadcrumb" class="max-w-full" [model]="menuItems"
    [home]="{ icon: ' pi pi-home' }"></p-breadcrumb>

<div class="container-fluid">
    <main role="main" class="">
        <router-outlet></router-outlet>
    </main>
</div>

// react/web/src/App.tsx
import React, { useState, useEffect, useRef } from 'react';
import logo from './logo.svg';
import './App.css';
import { Menu } from 'primereact/menu';
import { Toast } from 'primereact/toast';
import { Button } from 'primereact/button';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import BlankComponent from './main/Main';
import { DataService } from './service/data.service';

function App() {


  const toast = useRef(null);
  const menuLeft = useRef<Menu>(null!);
  /*
    var service = new DataService()
    var size = service.getSize();
  
    useEffect(() => {
      // Subscribe to changes in currentSize
      service.setSize("size1");
    }, []);
  
    useEffect(() => {
      // Check if currentSize has changed
      if (service.getSize() !== "size1") {
        // Do something when currentSize changes
        size = service.getSize();
        console.log("currentSize changed to: ", service.getSize());
      }
    }, [service.getSize()]);
  
    var level = service.getLevel();
  */
  const items = [
    { label: 'Level A', tabindex: "0", target: "_self" },
    { label: 'Level AA', tabindex: "0", target: "_self" },
    { label: 'Level AAA', tabindex: "0", target: "_self" },
    { separator: true },
    //{ label: 'Font size up 50%', command: () => upSize(), tabindex: "0" },
    //{ label: 'Font size down 50%', command: () => downSize(), tabindex: "0" },
  ]
  /*
    const upSize = () => {
      if (size == "size1") {
        service.setSize("size15");
        size = service.currentSize
        console.log(service.getSize());
        return
      }
      if (size == "size15") {
        service.setSize("size2");
        size = service.currentSize
        console.log(service.getSize());
        return
      }
      if (size == "size2") {
        service.setSize("size2");
        size = service.currentSize
        console.log(service.getSize());
        return
      }
    }
  
    const downSize = () => {
      if (size == "size1") {
        service.setSize("size1");
        size = service.currentSize
        console.log(service.getSize());
        return
      }
      if (size == "size15") {
        service.setSize("size1");
        size = service.currentSize
        console.log(service.getSize());
        return
      }
      if (size == "size2") {
        service.setSize("size15");
        size = service.currentSize
        console.log(service.getSize());
        return
      }
    }
  */

  return (
    <div className="App">
      <header>
        <h2>Accessibility Test</h2>
        <nav className="navbar">
          <ul className="navLinks">
            <li><a href="" tabIndex={0} target="_self">Home</a></li>
            <li><a href="/register/A" tabIndex={0} target="_self">About</a></li>
            <li><a href="#" tabIndex={0} target="_self">Contact</a></li>
          </ul>
        </nav>
        <div className='abutton'>
          <Toast ref={toast}></Toast>
          <Menu model={items} popup ref={menuLeft} id="popup_menu_left" />
          <Button label="a11y menu" icon="pi pi-align-left" className="mr-2"
            onClick={(event) => menuLeft.current.toggle(event)} aria-controls="popup_menu_left" aria-haspopup />
          <div>
          </div>
        </div >
      </header >
      <BrowserRouter>
        <Routes>
          <Route path='/' element={<DataService><BlankComponent /></DataService>} />
        </Routes>
      </BrowserRouter>
    </div >
  );
}

export default App;
