// angular/web/src/app/main-aaa/main-aaa.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { MenuItem } from "primeng/api";
import { DataService } from '../service/data.service';
import { Router } from '@angular/router';
import { LocationService } from '../service/location.service';

@Component({
  selector: 'app-main-aaa',
  templateUrl: './main-aaa.component.html',
  styleUrls: ['./main-aaa.component.css']
})
export class MainAAAComponent implements OnDestroy, OnInit {
  menuItems: MenuItem[];
  menuItem: MenuItem = { label: 'home', url: 'main/A', preserveFragment: true }
  menuHome: MenuItem;
  size: string;
  validated: boolean;
  isAdult: boolean;
  firstNameExists: boolean;
  lastNameExistst: boolean;
  userNameExistst: boolean;
  emailValid: boolean;

  readonly emailRegex: RegExp = /^.*@hft.de$/;


  constructor(private data: DataService, private location: LocationService, private router: Router) {
  }
  ngOnDestroy(): void {
    this.location.removeMenu();
  }


  ngOnInit(): void {
    this.data.currentMessage.subscribe(message => this.size = message)
    this.location.currentLocation = 'main';
    this.menuHome = { icon: "pi pi-home" }
    this.location.appendMenu(this.menuItem);
    this.location.breadcrumbLocation.forEach(element => {
      console.log(element);
    });
    this.menuItems = this.location.breadcrumbLocation;
  }

  handleClick(link: string) {
    this.redirectToAnotherPage(link);
  }

  handleKeyDown(event: KeyboardEvent, link: string) {
    if (event.key === 'Enter') {
      this.redirectToAnotherPage(link);
    }
  }

  redirectToAnotherPage(link: string) {
    this.router.navigate(['/' + link]);
  }

  validate(): boolean {
    if (this.firstNameExists && this.lastNameExistst &&
      this.emailValid && this.isAdult) {
      this.validated = true;
      return true;
    }
    return false;
  }

  checkEmailValid(mail: string): void {
    this.emailValid = this.emailRegex.test(mail);
    this.validate();
  }

  getHeaderClass(): string {
    if (this.size == "size1") {
      return "headerClass-one"
    }
    if (this.size == "size15") {
      return "headerClass-half"
    }
    if (this.size == "size2") {
      return "headerClass-two"
    }
    return "headerClass-one";

  }
}

<h1>Home Level AAA</h1>
<div class="contentContainer">
    <p-card (click)="handleClick('/sub/A')" (keydown)="handleKeyDown($event, '/sub/A')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="topic card" src="../../assets/gordonPlant.jpg" />
        </ng-template>
        <h3 [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Topic 1</h3>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">very
            Interesting</p>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
    <p-card (click)="handleClick('/sub/A')" (keydown)="handleKeyDown($event, '/sub/A')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="topic card" src="../../assets/pexels-chris-hepworth-16047549.jpg" />
        </ng-template>
        <h3 [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Topic 1</h3>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">very
            Interesting</p>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
    <p-card (click)="handleClick('/sub/A')" (keydown)="handleKeyDown($event, '/sub/A')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="topic card" src="../../assets/pexels-stijn-dijkstra-16747506 (1).jpg" />
        </ng-template>
        <h3 [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Topic 1</h3>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">very
            Interesting</p>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
    <p-card (click)="handleClick('/sub/A')" (keydown)="handleKeyDown($event, '/sub/A')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="topic card" src="../../assets/pexels-josh-withers-16978839.jpg" />
        </ng-template>
        <h3 [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Topic 1</h3>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">very
            Interesting</p>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
    <p-card (click)="handleClick('/sub/A')" (keydown)="handleKeyDown($event, '/sub/A')" tabindex="0"
        [style]="{ width: '360px' }">
        <ng-template pTemplate="header">
            <img alt="Card" src="../../assets/pexels-christyn-reyes-13458334.jpg" />
        </ng-template>
        <h3 [ngClass]="{'h-one' : size == 'size1','h-half' : size == 'size15', 'h-two' : size == 'size2' }">
            Topic 1</h3>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">very
            Interesting</p>
        <p [ngClass]="{'label' : size == 'size1', 'label-half' : size == 'size15', 'label-two' : size == 'size2' }">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
            numquam
            deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse,
            cupiditate
            neque
            quas!
        </p>

    </p-card>
</div>

// react/web/src/mainAAA/MainAAA.tsx
import React, { Component, useEffect, useState } from 'react';
import { Card } from 'primereact/card';
import gordon from '../assets/gordonPlant.jpg'
import chris from '../assets/pexels-chris-hepworth-16047549.jpg'
import christ from '../assets/pexels-christyn-reyes-13458334.jpg'
import josh from '../assets/pexels-josh-withers-16978839.jpg'
import stjin from '../assets/pexels-stijn-dijkstra-16747506 (1).jpg'
import MyService from '../service/Service';
import './MainAAA.css'

interface MainAAAProps {
    size: string;
    level: string;
    service: MyService;
    foreground: string;
    background: string;
}



const MainAAA: React.FC<MainAAAProps> = ({ service, size, level, foreground, background }) => {
    const [currentLevel, setCurrentLevel] = useState<string>('AAA');
    useEffect(() => {
        service.updateCurrentLevel(currentLevel)
    }, [])




    const headerGordon = (
        <img alt="Card" src={gordon} />
    );
    const headerChris = (
        <img alt="Card" src={chris} />
    );
    const headerChrist = (
        <img alt="Card" src={christ} />
    );
    const headerJosh = (
        <img alt="Card" src={josh} />
    );
    const headerStjin = (
        <img alt="Card" src={stjin} />
    );
    return (
        <div>
            <div className="welcome">
                <h1 tabIndex={0} style={{ color: foreground, backgroundColor: background }}>Welcome</h1>
                <h2 tabIndex={0} style={{ color: foreground, backgroundColor: background }} >Home Level AAA</h2>
            </div>
            <div className='contentContainer'>
                <div className="card">
                    <Card className='card' title="Title" subTitle="Subtitle" header={headerGordon} style={{ color: foreground, backgroundColor: background }}>
                        <p style={{ color: foreground, backgroundColor: background }}
                            className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card title="Title" subTitle="Subtitle" className='card' header={headerChris} style={{ color: foreground, backgroundColor: background }} >
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card title="Title" subTitle="Subtitle" header={headerChrist} className="card" style={{ color: foreground, backgroundColor: background }}>
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card title="Title" subTitle="Subtitle" header={headerJosh} className="card" style={{ color: foreground, backgroundColor: background }}>
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
                <div className="card">
                    <Card title="Title" subTitle="Subtitle" header={headerStjin} className="card" style={{ color: foreground, backgroundColor: background }}>
                        <p className={`${size === 'size1' ? 'para-one' : size === 'size2' ? 'para-two' : 'para-half'}`} style={{ color: foreground, backgroundColor: background }}>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae
                            numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque quas!
                        </p>
                    </Card>
                </div>
            </div >
        </div>
    );
};

export default MainAAA;
